[package]
name = "proxy-manager"
version = "0.1.0"
edition = "2024"

default-run = "proxy-manager"

[[bin]]
name = "proxy-manager"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "1.6"
bollard = "0.17"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
directories = "5.0"
futures-util = "0.3"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
thiserror = "1.0"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
tempfile = "3.10"
